name 'sitedbaas-windows'
maintainer 'Chef Demos'
maintainer_email 'chef-demos@chef.io'
license 'all_rights'
description 'Installs/Configures sitedbaas-windows'
long_description 'Installs/Configures sitedbaas-windows'
version '0.1.14'
depends 'windows'
