name 'sitedbaas-windows'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures sitedbaas-windows'
long_description 'Installs/Configures sitedbaas-windows'
version '0.1.1'
depends 'windows'
